<?php

declare(strict_types=1);

namespace App\Notifications;

use App\Models\Alert;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\BroadcastMessage;
use Illuminate\Notifications\Notification;

class BudgetAlertTriggeredNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        private Alert $alert,
    ) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['database', 'broadcast'];
    }

    public function toBroadcast(object $notifiable): BroadcastMessage
    {
        return new BroadcastMessage($this->toArray($notifiable));
    }

    /**
     * @return array{
     *   type: string,
     *   alert_id: string,
     *   budget_id: string|null,
     *   cycle_id: string|null,
     *   goal_id: string|null,
     *   severity: string|null,
     *   summary: string,
     *   deep_link: array{
     *     route: string,
     *     params: array{
     *       cycle_id: string|null,
     *       goal_id: string|null
     *     }
     *   }
     * }
     */
    public function toArray(object $notifiable): array
    {
        $context = $this->alert->getAttribute('context');

        return [
            'type' => 'budget_alert',
            'alert_id' => (string) $this->alert->getKey(),
            'budget_id' => $this->stringOrNull($this->alert->getAttribute('budget_id')),
            'cycle_id' => $this->stringOrNull($this->alert->getAttribute('cycle_id')),
            'goal_id' => $this->stringOrNull($this->alert->getAttribute('goal_id')),
            'severity' => $this->stringOrNull($this->alert->getAttribute('severity')),
            'summary' => is_array($context)
                ? (string) data_get($context, 'reason', 'Budget alert generated by background checks.')
                : 'Budget alert generated by background checks.',
            'deep_link' => [
                'route' => 'dashboard',
                'params' => [
                    'cycle_id' => $this->stringOrNull($this->alert->getAttribute('cycle_id')),
                    'goal_id' => $this->stringOrNull($this->alert->getAttribute('goal_id')),
                ],
            ],
        ];
    }

    private function stringOrNull(mixed $value): ?string
    {
        return is_string($value) ? $value : null;
    }
}
